<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
<p>
    Votre demande a été prise en compte<br />
    <br />
    Votre numéro d'incident a été ouvert sur le projet <?= $this->projectName ?> avec le ticket numéro <?= $this->idIssue ?>
</p>
</body>
</html>